/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseDivider: typeof import('./components/base/BaseDivider.vue')['default']
    BaseImageViewer: typeof import('./components/base/BaseImageViewer.vue')['default']
    BaseModal: typeof import('./components/base/BaseModal.vue')['default']
    BaseStarButton: typeof import('./components/base/BaseStarButton.vue')['default']
    BaseTabs: typeof import('./components/base/BaseTabs.vue')['default']
    BoothBrandDirectory: typeof import('./components/exhibition/BoothBrandDirectory.vue')['default']
    BoothBrandDirectoryModal: typeof import('./components/exhibition/BoothBrandDirectoryModal.vue')['default']
    BrandEditModal: typeof import('./components/exhibition/BrandEditModal.vue')['default']
    BrandModal: typeof import('./components/exhibition/BrandModal.vue')['default']
    ExhibitionActivities: typeof import('./components/exhibition/ExhibitionActivities.vue')['default']
    ExhibitionArticleItem: typeof import('./components/exhibition/ExhibitionArticleItem.vue')['default']
    ExhibitionBrandHeader: typeof import('./components/exhibition/ExhibitionBrandHeader.vue')['default']
    ExhibitionContact: typeof import('./components/exhibition/ExhibitionContact.vue')['default']
    ExhibitionExperience: typeof import('./components/exhibition/ExhibitionExperience.vue')['default']
    ExhibitionFavorites: typeof import('./components/exhibition/ExhibitionFavorites.vue')['default']
    ExhibitionFavoritesModal: typeof import('./components/exhibition/ExhibitionFavoritesModal.vue')['default']
    ExhibitionGiftItem: typeof import('./components/exhibition/ExhibitionGiftItem.vue')['default']
    ExhibitionInfoModal: typeof import('./components/exhibition/ExhibitionInfoModal.vue')['default']
    ExhibitionMenu: typeof import('./components/exhibition/ExhibitionMenu.vue')['default']
    ExhibitionMenuPicker: typeof import('./components/exhibition/ExhibitionMenuPicker.vue')['default']
    ExhibitionProductItem: typeof import('./components/exhibition/ExhibitionProductItem.vue')['default']
    FavoriteButton: typeof import('./components/base/FavoriteButton.vue')['default']
    ProductGallery: typeof import('./components/exhibition/ProductGallery.vue')['default']
  }
}
