/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseDialog: typeof import('./components/base/BaseDialog.vue')['default']
    BaseDivider: typeof import('./components/base/BaseDivider.vue')['default']
    BaseStarButton: typeof import('./components/base/BaseStarButton.vue')['default']
    BaseTabBar: typeof import('./components/base/BaseTabBar.vue')['default']
    BaseTabs: typeof import('./components/base/BaseTabs.vue')['default']
    BoothBrandHeader: typeof import('./components/exhibition/BoothBrandHeader.vue')['default']
    BoothDetail: typeof import('./components/exhibition/BoothDetail.vue')['default']
    BoothProductCard: typeof import('./components/exhibition/BoothProductCard.vue')['default']
    BrandEditDialog: typeof import('./components/exhibition/BrandEditDialog.vue')['default']
    BrandListPanel: typeof import('./components/exhibition/BrandListPanel.vue')['default']
    ChatroomPanel: typeof import('./components/exhibition/ChatroomPanel.vue')['default']
    DebugMapPanel: typeof import('./components/exhibition/DebugMapPanel.vue')['default']
    ExhibitionBrandHeader: typeof import('./components/exhibition/ExhibitionBrandHeader.vue')['default']
    ExhibitionGiftItem: typeof import('./components/exhibition/ExhibitionGiftItem.vue')['default']
    ExhibitionLayout: typeof import('./components/exhibition/ExhibitionLayout.vue')['default']
    ExhibitionMap: typeof import('./components/exhibition/ExhibitionMap.vue')['default']
    ExhibitionProductItem: typeof import('./components/exhibition/ExhibitionProductItem.vue')['default']
    FavoriteButton: typeof import('./components/base/FavoriteButton.vue')['default']
    LeaderboardPanel: typeof import('./components/exhibition/LeaderboardPanel.vue')['default']
    ProductDetailDialog: typeof import('./components/exhibition/ProductDetailDialog.vue')['default']
    ProductEditDialog: typeof import('./components/exhibition/ProductEditDialog.vue')['default']
    ProductGallery: typeof import('./components/exhibition/ProductGallery.vue')['default']
    WishlistPanel: typeof import('./components/exhibition/WishlistPanel.vue')['default']
  }
}
